language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install

script: vendor/bin/phpunit --coverage-clover=coverage.xml --bootstrap=tests/bootstrap.php tests/

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ] ; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
